on:
  push:
    branches:
      - main
      - github-actions

permissions:
      contents: read
      packages: write

name: Publish on push to main
jobs:
  publishDockerImageToGHCR:
    name: Publish Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Registry
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: ghcr.io
    - name: Build & publish
      uses: parkr/actions/docker-make@main
      with:
        args: docker-release -e REV=${{ github.sha }}
  publishDockerImage:
    name: Publish Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Registry
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Build & publish
      uses: parkr/actions/docker-make@main
      with:
        args: docker-release -e REV=${{ github.sha }}
