on:
  push:
    branches:
      - main
      - github-actions

permissions:
      contents: read
      packages: write

name: Publish on push to main
jobs:
  publishDockerImageToGHCR:
    name: Publish Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Registry
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: ghcr.io
    - name: Build & publish
      uses: parkr/actions/docker-make@main
      with:
        args: docker-release -e REV=${{ github.sha }}
  publishDockerImage:
    name: Publish Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Docker meta
      id: meta_step
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
            docker.io/parkr/instapaper-archive
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=sha
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_step.outputs.tags }}
          labels: ${{ steps.meta_step.outputs.labels }}
